[tool.commitizen]
name = "cz_customize"

[tool.commitizen.customize]
message_template = "{{change_type}}{% if breaking %}!{% endif %}: {{headline}}\n{{body}}{% if breaking %}\n\nBREAKING CHANGE{% endif %}"
example = "feature: this feature enables customization through config file"
schema = "<type>: <body>"
bump_pattern = "^(break|feature|fix|tune)"
bump_map = {"break" = "MAJOR", "feature" = "MINOR", "fix" = "PATCH", "tune" = "PATCH"}
info_path = "cz_customize_info.txt"

[[tool.commitizen.customize.questions]]
type = "list"
name = "change_type"
choices = [
    {value = "feature", name = "feature: Ads a new feature."},
    {value = "fix", name = "fix: Corrects an error in an existing feature."},
    {value = "tune", name = "tune: Tunes/improves an existing feature."},
    {value = "refactor", name = "refactor: Refactors code."},
    {value = "doc", name = "doc: Adds documentation."},
    {value = "revert", name = "revert: A revert commit."},
]
message = "Select the type of change you are committing"

[[tool.commitizen.customize.questions]]
type = "input"
name = "headline"
message = "Headline:"

[[tool.commitizen.customize.questions]]
type = "confirm"
name = "breaking"
default = false
message = "Is this a breaking change?"

[[tool.commitizen.customize.questions]]
type = "text"
name = "body"
message = "<optional> Body:"
